### ISSUE TITLE
Learn how to host local page

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#1]
## Summary

We should learn and make an install script or write-up on how to set up a basic "hello world" page that can be viewed from computers on the same network.

## Other links or relevant information

Maybe node.js for serving content?  I don't know yet.

## Task List
- [ ] Decide how to serve the page.
- [ ] Make a "hello world" page for proof of concept.
- [ ] Pull something from the database and display it.
- [ ] Pull data from the database and graph it.
- [ ] Make more interesting graphs.

#### 📈 Progress (0-10): 0
