### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by lo9key** [OregonStateRocketry/30k2018-CS-Capstone#2]
## Summary

Set up a database for the parsing program to write to, and for the localhost to pull from to generate pages and dynamic graphs.

## Other links or relevant information

Maybe [postgresql](https://www.postgresql.org/) or mysql?

## Task List
- [ ] Decide on security.  ( suggested: localhost only )
- [x] Draft some default tables and fields
- [x] Add a few rows of example data

#### 📈 Progress (0-10): 0
